id: P4B7F8F86
initial_creation_type: ocr
source_metadata:
  volumes:
    874bb66bc3a74f35b3551046a4364147:
      base_file: v011.txt
      image_group_id: I1PD95856
      title: དཔལ་བཅོམ་ལྡན་འདས་ཀྱི་མངོན་པར་རྟོགས་པ།
      total_pages: 2107
      volume_number: 11
