id: DB9224EC7
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2021-12-31T06:39:22+00:00'
last_modified: '2022-05-26T07:55:49.872032+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/a7eec5e12ddce18d0ed1dbb732a42cf48f94dd09/openpecha/formatters/hfml.py
source_metadata:
  base:
    ecd2:
      image_group_id: I1PD95856
      title: དཔལ་བཅོམ་ལྡན་འདས་ཀྱི་མངོན་པར་རྟོགས་པ།
      total_pages: 2107
      order: 11
      base_file: ecd2.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
